In [21]:
Hello Harshal

SyntaxError: invalid syntax (2648255137.py, line 1)

In [ ]:
Hello Harshal

SyntaxError: invalid syntax (2648255137.py, line 1)

In [ ]:
print("Hello Harshal")

Hello Harshal

In [ ]:
import pandas as pdf

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pf

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
import pandas as pdf

ModuleNotFoundError: No module named 'pandas'

In [ ]:
pip install pandas openpyxl

Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\harshal shende\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\users\harshal shende\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------ --------------------------------- 1.6/9.8 MB 7.2 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.8 MB 4.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.4/9.8 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ---------- ----------------------------- 2.6/9.8 MB 2.0 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ----------- ---------------------------- 2.9/9.8 MB 1.6 MB/s eta 0:00:05
   ------------ --------------------------- 3.1/9.8 MB 1.5 MB/s eta 0:00:05
   ---------------- ----------------------- 3.9/9.8 MB 1.6 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.8 MB 1.8 MB/s eta 0:00:03
   ----------------------- ---------------- 5.8/9.8 MB 2.0 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.8 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.8 MB 2.0 MB/s eta 0:00:02
   ----------------------------- ---------- 7.3/9.8 MB 2.1 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.8 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.8 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.3 MB/s  0:00:04
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.4 MB 5.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.4 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.8/12.4 MB 2.9 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.4 MB 2.8 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.4 MB 3.2 MB/s eta 0:00:03
   --------------- ------------------------ 4.7/12.4 MB 3.6 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.4 MB 4.0 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.4 MB 4.6 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.4 MB 4.8 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 4.8 MB/s  0:00:02
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, et-xmlfile, pandas, openpyxl

   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   ---------------------------------------- 0/5 [tzdata]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   -------- ------------------------------- 1/5 [numpy]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   ------------------------ --------------- 3/5 [pandas]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   -------------------------------- ------- 4/5 [openpyxl]
   ---------------------------------------- 5/5 [openpyxl]

Successfully installed et-xmlfile-2.0.0 numpy-2.5.1 openpyxl-3.1.5 pandas-3.0.5 tzdata-2026.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("../Customer_Transactions_Dataset.xlsx")

In [ ]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       200 non-null    str
 1   Customer_ID          200 non-null    str
 2   Transaction_Date     200 non-null    str
 3   Product_ID           200 non-null    str
 4   Product_Category     200 non-null    str
 5   Quantity             200 non-null    int64
 6   Unit_Price           200 non-null    int64
 7   Total_Amount         200 non-null    int64
 8   Payment_Method       200 non-null    str
 9   Transaction_Status   200 non-null    str
 10  Acquisition_Channel  200 non-null    str
 11  Country              200 non-null    str
 12  City                 200 non-null    str
 13  Device_Type          200 non-null    str
dtypes: int64(3), str(11)
memory usage: 22.0 KB

In [ ]:
df.shape

(200, 14)

In [ ]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Product_ID',
       'Product_Category', 'Quantity', 'Unit_Price', 'Total_Amount',
       'Payment_Method', 'Transaction_Status', 'Acquisition_Channel',
       'Country', 'City', 'Device_Type'],
      dtype='str')

In [ ]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [ ]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       200 non-null    str
 1   Customer_ID          200 non-null    str
 2   Transaction_Date     200 non-null    str
 3   Product_ID           200 non-null    str
 4   Product_Category     200 non-null    str
 5   Quantity             200 non-null    int64
 6   Unit_Price           200 non-null    int64
 7   Total_Amount         200 non-null    int64
 8   Payment_Method       200 non-null    str
 9   Transaction_Status   200 non-null    str
 10  Acquisition_Channel  200 non-null    str
 11  Country              200 non-null    str
 12  City                 200 non-null    str
 13  Device_Type          200 non-null    str
dtypes: int64(3), str(11)
memory usage: 22.0 KB

In [ ]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [ ]:
git status

SyntaxError: invalid syntax (3528599804.py, line 1)

In [ ]:
!git status

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	../../../.bash_history
	../../../.codeium/
	../../../.copilot/
	../../../.docker/
	../../../.git-for-windows-updater
	../../../.gitconfig
	../../../.idlerc/
	../../../.ipython/
	../../../.lesshst
	../../../.redis-for-vscode/
	../../../.vscode-shared/
	../../../.vscode/
	../../../3D Objects/
	../../../AppData/
	../../../Contacts/
	../../
	../../../Documents/
	../../../Downloads/
	../../../Favorites/
	../../../IntelGraphicsProfiles/
	../../../Links/
	../../../Microsoft/
	../../../Music/
	../../../NTUSER.DAT
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TM.blf
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TMContainer00000000000000000001.regtrans-ms
	../../../NTUSER.DAT{4d73a84d-d552-11ef-860a-2839268ef0f6}.TMContainer00000000000000000002.regtrans-ms
	../../../OneDrive/
	../../../Pictures/
	../../../Saved Games/
	../../../Searches/
	../../../Videos/
	../../../demo.txt
	../../../go/
	../../../ntuser.dat.LOG1
	../../../ntuser.dat.LOG2
	../../../ntuser.ini
	../../../python/

nothing added to commit but untracked files present (use "git add" to track)

warning: could not open directory 'AppData/Local/Application Data/': Permission denied
warning: could not open directory 'Application Data/': Permission denied
warning: could not open directory 'Cookies/': Permission denied
warning: could not open directory 'Local Settings/': Permission denied
warning: could not open directory 'My Documents/': Permission denied
warning: could not open directory 'NetHood/': Permission denied
warning: could not open directory 'PrintHood/': Permission denied
warning: could not open directory 'Recent/': Permission denied
warning: could not open directory 'SendTo/': Permission denied
warning: could not open directory 'Start Menu/': Permission denied
warning: could not open directory 'Templates/': Permission denied

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_excel("Customer_Transactions_Dataset.xlsx")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Customer_Transactions_Dataset.xlsx'

In [ ]:
import pandas as pd

df = pd.read_excel("../Customer_Transactions_Dataset.xlsx")

df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [ ]:
df.shape

(200, 14)

In [ ]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Product_ID',
       'Product_Category', 'Quantity', 'Unit_Price', 'Total_Amount',
       'Payment_Method', 'Transaction_Status', 'Acquisition_Channel',
       'Country', 'City', 'Device_Type'],
      dtype='str')

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Transaction_ID       200 non-null    str
 1   Customer_ID          200 non-null    str
 2   Transaction_Date     200 non-null    str
 3   Product_ID           200 non-null    str
 4   Product_Category     200 non-null    str
 5   Quantity             200 non-null    int64
 6   Unit_Price           200 non-null    int64
 7   Total_Amount         200 non-null    int64
 8   Payment_Method       200 non-null    str
 9   Transaction_Status   200 non-null    str
 10  Acquisition_Channel  200 non-null    str
 11  Country              200 non-null    str
 12  City                 200 non-null    str
 13  Device_Type          200 non-null    str
dtypes: int64(3), str(11)
memory usage: 22.0 KB

In [ ]:
df.describe()

         Quantity  Unit_Price  Total_Amount
count  200.000000  200.000000    200.000000
mean     3.070000  256.950000    778.910000
std      1.454537  141.328007    598.395091
min      1.000000   19.000000     33.000000
25%      2.000000  129.500000    294.750000
50%      3.000000  241.500000    624.500000
75%      4.000000  376.750000   1121.250000
max      5.000000  496.000000   2480.000000

In [ ]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull.sum()

NameError: name 'df' is not defined

In [ ]:
df.isnull.sum()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

In [ ]:
import pandas as pd

df = pd.read_excel("../Customer_Transactions_Dataset.xlsx")

In [ ]:
df.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Transaction_Status"].value_counts()

Transaction_Status
Completed    159
Refunded      22
Failed        19
Name: count, dtype: int64

In [ ]:
df_clean = df.copy()

In [ ]:
df_clean["Transaction_Status"].value_counts()

Transaction_Status
Completed    159
Refunded      22
Failed        19
Name: count, dtype: int64

In [ ]:
df_clean = df_clean[df_clean["Transaction_Status"] == "Completed"]

In [ ]:
df_clean["Transaction_Status"].value_counts()

Transaction_Status
Completed    159
Name: count, dtype: int64

In [ ]:
df_clean["Customer_ID"].isnull().sum()

np.int64(0)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean["Transaction_Date"].dtype

In [ ]:
df_clean["Transaction_Date"] = pd.to_datetime(
    df_clean["Transaction_Date"],
    errors="coerce"
)

In [ ]:
df_clean["Transaction_Date"] = pd.to_datetime(
    df_clean["Transaction_Date"],
    errors="coerce"
)

In [ ]:
df_clean["Transaction_Date"].dtype

dtype('<M8[us]')

In [ ]:
df_clean["Transaction_Date"].isnull().sum()

np.int64(0)

In [ ]:
first_transaction = df_clean.groupby("Customer_ID")["Transaction_Date"].min()

In [ ]:
first_transaction.head()

Customer_ID
C001   2025-12-03
C002   2025-05-01
C004   2025-04-20
C010   2025-10-25
C013   2025-07-30
Name: Transaction_Date, dtype: datetime64[us]

In [ ]:
first_transaction = first_transaction.reset_index()

In [ ]:
first_transaction.head()

  Customer_ID Transaction_Date
0        C001       2025-12-03
1        C002       2025-05-01
2        C004       2025-04-20
3        C010       2025-10-25
4        C013       2025-07-30

In [ ]:
first_transaction.rename(
    columns={"Transaction_Date": "First_Transaction_Date"},
    inplace=True
)

In [ ]:
first_transaction["Cohort_Month"] = (
    first_transaction["First_Transaction_Date"]
    .dt.to_period("M")
)

In [ ]:
first_transaction.head()

  Customer_ID First_Transaction_Date Cohort_Month
0        C001             2025-12-03      2025-12
1        C002             2025-05-01      2025-05
2        C004             2025-04-20      2025-04
3        C010             2025-10-25      2025-10
4        C013             2025-07-30      2025-07

In [ ]:
df_clean = df_clean.merge(
    first_transaction[["Customer_ID", "Cohort_Month"]],
    on="Customer_ID",
    how="left"
)

In [ ]:
df_clean.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type,Cohort_Month
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop,2025-03
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet,2025-06
2,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet,2025-01
3,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile,2025-02
4,T0006,C104,2025-04-29,P045,Electronics,1,485,485,NetBanking,Completed,Facebook,India,Bengaluru,Tablet,2025-03

In [ ]:
df_clean = df_clean.merge(
    first_transaction[["Customer_ID", "Cohort_Month"]],
    on="Customer_ID",
    how="left"
)

In [ ]:
df_clean.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type,Cohort_Month_x,Cohort_Month_y
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop,2025-03,2025-03
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet,2025-06,2025-06
2,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet,2025-01,2025-01
3,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile,2025-02,2025-02
4,T0006,C104,2025-04-29,P045,Electronics,1,485,485,NetBanking,Completed,Facebook,India,Bengaluru,Tablet,2025-03,2025-03

In [ ]:
df_clean["Cohort_Month"].isnull().sum()

KeyError: 'Cohort_Month'

In [ ]:
df_clean = df_clean.merge(
    first_transaction[["Customer_ID", "Cohort_Month"]],
    on="Customer_ID",
    how="left"
)

In [ ]:
df_clean.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type,Cohort_Month_x,Cohort_Month_y,Cohort_Month
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop,2025-03,2025-03,2025-03
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet,2025-06,2025-06,2025-06
2,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet,2025-01,2025-01,2025-01
3,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile,2025-02,2025-02,2025-02
4,T0006,C104,2025-04-29,P045,Electronics,1,485,485,NetBanking,Completed,Facebook,India,Bengaluru,Tablet,2025-03,2025-03,2025-03

In [ ]:
df_clean["Cohort_Month"].isnull().sum()

np.int64(0)

In [ ]:
df_clean.shape

(159, 17)

In [ ]:
df_clean["Cohort_Month"].isnull().sum()

np.int64(0)

In [ ]:
df_clean.dtypes

Transaction_ID                    str
Customer_ID                       str
Transaction_Date       datetime64[us]
Product_ID                        str
Product_Category                  str
Quantity                        int64
Unit_Price                      int64
Total_Amount                    int64
Payment_Method                    str
Transaction_Status                str
Acquisition_Channel               str
Country                           str
City                              str
Device_Type                       str
Cohort_Month_x              period[M]
Cohort_Month_y              period[M]
Cohort_Month                period[M]
dtype: object

In [ ]:
df_clean.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type,Cohort_Month_x,Cohort_Month_y,Cohort_Month
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop,2025-03,2025-03,2025-03
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet,2025-06,2025-06,2025-06
2,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet,2025-01,2025-01,2025-01
3,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile,2025-02,2025-02,2025-02
4,T0006,C104,2025-04-29,P045,Electronics,1,485,485,NetBanking,Completed,Facebook,India,Bengaluru,Tablet,2025-03,2025-03,2025-03

In [ ]:
df_clean.to_excel("../Output/Cleaned_Transaction_Data.xlsx", index=False)

In [ ]:
df_clean.to_excel("../Output/Cleaned_Transaction_Data.xlsx", index=False)

In [ ]:
df_clean.shape

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
import pandas as pd

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
import pandas as pd

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
import pandas as pd

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
import pandas as pd

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
import pandas as pd

In [ ]:
df_clean.shape

NameError: name 'df_clean' is not defined

In [ ]:
df_clean =

SyntaxError: invalid syntax (45305442.py, line 1)

In [ ]:
df_clean

NameError: name 'df_clean' is not defined

In [ ]:
df_clean = df.copy()

NameError: name 'df' is not defined

In [22]:
df_clean = df.copy()

NameError: name 'df' is not defined

In [1]:
df = pd.read_excel(...)

NameError: name 'pd' is not defined

In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("../Customer_Transactions_Dataset.xlsx")

In [4]:
df.head()

,Transaction_ID,Customer_ID,Transaction_Date,Product_ID,Product_Category,Quantity,Unit_Price,Total_Amount,Payment_Method,Transaction_Status,Acquisition_Channel,Country,City,Device_Type
0,T0001,C049,2025-03-12,P086,Beauty,3,296,888,UPI,Completed,Facebook,India,Hyderabad,Desktop
1,T0002,C103,2025-06-27,P014,Electronics,4,176,704,UPI,Completed,Facebook,India,Mumbai,Tablet
2,T0003,C044,2025-08-09,P005,Home,3,294,882,UPI,Failed,Email,India,Bengaluru,Desktop
3,T0004,C060,2025-01-30,P090,Fashion,1,233,233,UPI,Completed,Organic,India,Mumbai,Tablet
4,T0005,C111,2025-11-02,P001,Fashion,5,254,1270,Wallet,Completed,Organic,India,Hyderabad,Mobile

In [5]:
df_clean = df.copy()

In [6]:
df_clean.shape

(200, 14)

In [7]:
df_clean.columns

Index(['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Product_ID',
       'Product_Category', 'Quantity', 'Unit_Price', 'Total_Amount',
       'Payment_Method', 'Transaction_Status', 'Acquisition_Channel',
       'Country', 'City', 'Device_Type'],
      dtype='str')

In [8]:
df_clean.isnull().sum()

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Product_ID             0
Product_Category       0
Quantity               0
Unit_Price             0
Total_Amount           0
Payment_Method         0
Transaction_Status     0
Acquisition_Channel    0
Country                0
City                   0
Device_Type            0
dtype: int64

In [9]:
df_clean.duplicated().sum()

np.int64(0)

In [10]:
df_clean.dtypes

Transaction_ID           str
Customer_ID              str
Transaction_Date         str
Product_ID               str
Product_Category         str
Quantity               int64
Unit_Price             int64
Total_Amount           int64
Payment_Method           str
Transaction_Status       str
Acquisition_Channel      str
Country                  str
City                     str
Device_Type              str
dtype: object

In [11]:
df_clean["Transaction_Date"] = pd.to_datetime(
    df_clean["Transaction_Date"],
    errors="coerce"
)

In [12]:
df_clean["Transaction_Date"].dtype

dtype('<M8[us]')

In [13]:
df_clean["Transaction_ID"].duplicated().sum()

np.int64(0)

In [14]:
df_clean["Transaction_Status"].value_counts()

Transaction_Status
Completed    159
Refunded      22
Failed        19
Name: count, dtype: int64

In [15]:
df_clean = df_clean[df_clean["Transaction_Status"] == "Completed"].copy()

In [16]:
df_clean.shape

(159, 14)

In [17]:
df_clean.isnull().sum().sum()

np.int64(0)

In [18]:
df_clean.duplicated().sum()

np.int64(0)

In [19]:
df_clean["Cohort_Month"] = df_clean["Transaction_Date"].dt.to_period("M")

In [20]:
df_clean["Cohort_Month"].isnull().sum()

np.int64(0)

In [21]:
df_clean.shape

(159, 15)

In [22]:
git status

SyntaxError: invalid syntax (3528599804.py, line 1)

In [23]:
df_clean.to_excel("../Output/Cleaned_Transaction_Data.xlsx", index=False)

In [24]:
df_clean.to_excel("../Output/Cleaned_Transaction_Data.xlsx", index=False)